using System;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.UI.Accessibility;
using Windows.Win32.UI.WindowsAndMessaging;

namespace SwtorLogParser.Overlay.WinUi.Interop;

/// <summary>
/// Phase 10 (INT-01): all overlay Win32 interop, generated by the Microsoft.Windows.CsWin32 source
/// generator from <c>NativeMethods.txt</c> — replacing the WinForms <c>NativeMethods.cs</c> hand-written
/// P/Invoke. Wraps a single top-level window HWND and provides the native behaviours WinUI cannot
/// express: layered whole-window opacity + click-through (OVL-04/06), caption-style drag (OVL-05),
/// borderless tool-window / no-activate styles (INT-03), and HWND_TOPMOST re-assert on foreground
/// changes (INT-02 / BL-01).
/// </summary>
public sealed class WindowInterop : IDisposable
{
    // Extended window styles (stable Win32 values; kept local to avoid enum-cast churn).
    private const int GWL_EXSTYLE = -20;
    private const long WS_EX_TRANSPARENT = 0x00000020;
    private const long WS_EX_TOOLWINDOW = 0x00000080;
    private const long WS_EX_LAYERED = 0x00080000;
    private const long WS_EX_NOACTIVATE = 0x08000000;

    // Non-client drag (caption move loop) — same trick the WinForms ParserForm used.
    private const uint WM_NCLBUTTONDOWN = 0x00A1;
    private const nuint HTCAPTION = 2;

    // Virtual-key codes for the global click-through toggle chord (Ctrl+Alt+O).
    private const int VK_CONTROL = 0x11;
    private const int VK_MENU = 0x12; // Alt
    private const int VK_O = 0x4F;

    // HWND_TOPMOST = (HWND)(-1): place above all non-topmost windows on every re-assert.
    private static readonly HWND HWND_TOPMOST = new(-1);

    private readonly HWND _hwnd;

    // The WinEvent callback MUST be kept alive for the hook's lifetime — the unmanaged hook holds a raw
    // function pointer and will AccessViolation if the delegate is GC'd (CsWin32 #1162). Held in an
    // instance field; the owning window keeps this WindowInterop instance alive.
    private WINEVENTPROC? _foregroundProc;
    private UnhookWinEventSafeHandle? _foregroundHook;
    private bool _disposed;

    public WindowInterop(nint hwnd) => _hwnd = new HWND(hwnd);

    /// <summary>
    /// Applies the base overlay extended styles: tool-window (stays out of Alt-Tab) and no-activate
    /// (never steals focus from the game) — INT-03. Click-through is NOT applied here; it is an opt-in
    /// toggle (OVL-06, default off). NOTE: <c>WS_EX_LAYERED</c> is deliberately NOT used — on WinUI 3 it
    /// breaks the DirectComposition swapchain and the window renders invisibly. Translucency is provided
    /// by a WinUI Acrylic <c>SystemBackdrop</c> + a tint brush instead. Apply this AFTER the window is
    /// shown (no-activate before first show can suppress the initial paint).
    /// </summary>
    public void ApplyOverlayStyles()
    {
        var ex = CurrentExStyle();
        ex |= WS_EX_TOOLWINDOW | WS_EX_NOACTIVATE;
        SetExStyle(ex);
    }

    /// <summary>
    /// Toggles whole-window click-through (OVL-06). When enabled, <c>WS_EX_TRANSPARENT</c> makes the
    /// mouse pass straight through to the game; disabled restores normal hit-testing so the overlay is
    /// movable/interactive again (the default).
    /// </summary>
    public void SetClickThrough(bool enabled)
    {
        var ex = CurrentExStyle();
        ex = enabled ? ex | WS_EX_TRANSPARENT : ex & ~WS_EX_TRANSPARENT;
        SetExStyle(ex);
    }

    /// <summary>
    /// Starts a caption-style drag from a pointer-press on the drag handle (OVL-05): release the XAML
    /// pointer capture, then ask Windows to run its non-client move loop as if the title bar was grabbed —
    /// works on a borderless window, matching the WinForms <c>WM_NCLBUTTONDOWN</c>/<c>HTCAPTION</c> drag.
    /// </summary>
    public void BeginDrag()
    {
        PInvoke.ReleaseCapture();
        PInvoke.SendMessage(_hwnd, WM_NCLBUTTONDOWN, new WPARAM(HTCAPTION), default);
    }

    /// <summary>
    /// Re-asserts HWND_TOPMOST without moving/resizing/activating the window — the core of the BL-01 fix
    /// (INT-02). Called on construction and whenever the OS foreground window changes (a borderless game
    /// taking the foreground otherwise drops us out of the topmost band).
    /// </summary>
    public void ReassertTopmost() =>
        PInvoke.SetWindowPos(_hwnd, HWND_TOPMOST, 0, 0, 0, 0,
            SET_WINDOW_POS_FLAGS.SWP_NOMOVE | SET_WINDOW_POS_FLAGS.SWP_NOSIZE | SET_WINDOW_POS_FLAGS.SWP_NOACTIVATE);

    /// <summary>
    /// Hooks <c>EVENT_SYSTEM_FOREGROUND</c> so every foreground change re-asserts our topmost z-order
    /// (BL-01). Out-of-context hook → the callback runs on our thread's message loop.
    /// </summary>
    public void StartForegroundTopmostHook()
    {
        _foregroundProc = OnForegroundChanged;
        _foregroundHook = PInvoke.SetWinEventHook(
            PInvoke.EVENT_SYSTEM_FOREGROUND, PInvoke.EVENT_SYSTEM_FOREGROUND,
            null, _foregroundProc, 0, 0, PInvoke.WINEVENT_OUTOFCONTEXT);
        ReassertTopmost();
    }

    /// <summary>True while the Ctrl+Alt+O global toggle chord is held (polled — works without focus).</summary>
    public static bool IsToggleChordDown() =>
        IsDown(VK_CONTROL) && IsDown(VK_MENU) && IsDown(VK_O);

    private static bool IsDown(int vk) => (PInvoke.GetAsyncKeyState(vk) & 0x8000) != 0;

    private void OnForegroundChanged(
        HWINEVENTHOOK hook, uint @event, HWND hwnd, int idObject, int idChild, uint thread, uint time)
        => ReassertTopmost();

    private long CurrentExStyle() => PInvoke.GetWindowLongPtr(_hwnd, (WINDOW_LONG_PTR_INDEX)GWL_EXSTYLE);

    private void SetExStyle(long exStyle) =>
        PInvoke.SetWindowLongPtr(_hwnd, (WINDOW_LONG_PTR_INDEX)GWL_EXSTYLE, (nint)exStyle);

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _foregroundHook?.Dispose();
        _foregroundProc = null;
    }
}
